[FSRIFS_SETTINGS]
HUD_PORT=4867
VERBOSE=false


# =====================================================================
#             DOCUMENTATION & REFERENCE MANUAL (Read Only)
# =====================================================================
#
#  HUD_PORT: xxxx
#  --------------------------------------------------------------------
#  Defines the TCP port used to stream real-time FFmpeg progress data 
#  to the internal .NET HUD rendering engine.
#  Default: 4867.
#  
#  If connection errors occur because the port is already bound by another 
#  process, change this value.
#
#
#  VERBOSE:
#  --------------------------------------------------------------------
#  Controls the depth of technical data saved inside the log file.
#  true  - Writes deep real-time rendering statistics, Vulkan hardware 
#          initialization, and encoder details into the session log.
#  false - Keeps the session log file clean and compact, recording 
#          only essential messages and final execution results.
#
# =====================================================================
